=== michelemarzollo/ing-sw-2018-labate-maffiola-marzollo/src/main/resources/it/polimi/se2018/model/pattern.xsd
<?xml version="1.0" encoding="utf-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:pat="http://se2018.polimi.it/pattern"
           targetNamespace="http://se2018.polimi.it/pattern"
           elementFormDefault="qualified">

    <xs:simpleType name="range1to6">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="6"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="difficultyType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="3"/>
            <xs:maxInclusive value="6"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="rowIndex">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="4"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="columnIndex">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="dieColour">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BLUE"/>
            <xs:enumeration value="GREEN"/>
            <xs:enumeration value="PURPLE"/>
            <xs:enumeration value="RED"/>
            <xs:enumeration value="YELLOW"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="gridDescription">
        <xs:sequence>
            <xs:element name="cell" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="valueRestriction" type="pat:range1to6"/>
                        <xs:element name="colourRestriction" type="pat:dieColour"/>
                    </xs:choice>

                    <xs:attribute name="row" use="required" type="pat:rowIndex"/>
                    <xs:attribute name="col" use="required" type="pat:columnIndex"/>

                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="pattern">
        <xs:complexType>
            <xs:all>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="difficulty" type="pat:difficultyType"/>
                <xs:element name="grid" type="pat:gridDescription" minOccurs="0">
                    <!--Prohibits multiple cell definitions-->
                    <xs:unique name="cellCoordinates">
                        <xs:selector xpath="pat:cell"/>
                        <xs:field xpath="@row"/>
                        <xs:field xpath="@col"/>
                    </xs:unique>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== michelemarzollo/ing-sw-2018-labate-maffiola-marzollo/src/main/resources/it/polimi/se2018/model/patterns/xmls/lux_astram.xml
<?xml version="1.0" encoding="UTF-8" ?>

<pattern xmlns="http://se2018.polimi.it/pattern"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://se2018.polimi.it/pattern ../pattern.xsd">
    <name>Lux Astram</name>
    <difficulty>5</difficulty>
    <grid>
        <cell row="1" col="2">
            <valueRestriction>1</valueRestriction>
        </cell>
        <cell row="1" col="3">
            <colourRestriction>GREEN</colourRestriction>
        </cell>
        <cell row="1" col="4">
            <colourRestriction>PURPLE</colourRestriction>
        </cell>
        <cell row="1" col="5">
            <valueRestriction>4</valueRestriction>
        </cell>
        <cell row="2" col="1">
            <valueRestriction>6</valueRestriction>
        </cell>
        <cell row="2" col="2">
            <colourRestriction>PURPLE</colourRestriction>
        </cell>
        <cell row="2" col="3">
            <valueRestriction>2</valueRestriction>
        </cell>
        <cell row="2" col="4">
            <valueRestriction>5</valueRestriction>
        </cell>
        <cell row="2" col="5">
            <colourRestriction>GREEN</colourRestriction>
        </cell>
        <cell row="3" col="1">
            <valueRestriction>1</valueRestriction>
        </cell>
        <cell row="3" col="2">
            <colourRestriction>GREEN</colourRestriction>
        </cell>
        <cell row="3" col="3">
            <valueRestriction>5</valueRestriction>
        </cell>
        <cell row="3" col="4">
            <valueRestriction>3</valueRestriction>
        </cell>
        <cell row="3" col="5">
            <colourRestriction>PURPLE</colourRestriction>
        </cell>
    </grid>
</pattern>

=== michelemarzollo/ing-sw-2018-labate-maffiola-marzollo/src/main/resources/it/polimi/se2018/model/patterns/xmls/sun_catcher.xml
<?xml version="1.0" encoding="UTF-8" ?>

<pattern xmlns="http://se2018.polimi.it/pattern"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://se2018.polimi.it/pattern ../pattern.xsd">
    <name>Sun Catcher</name>
    <difficulty>3</difficulty>
    <grid>
        <cell row="1" col="2">
            <colourRestriction>BLUE</colourRestriction>
        </cell>
        <cell row="1" col="3">
            <valueRestriction>2</valueRestriction>
        </cell>
        <cell row="1" col="5">
            <colourRestriction>YELLOW</colourRestriction>
        </cell>
        <cell row="2" col="2">
            <valueRestriction>4</valueRestriction>
        </cell>
        <cell row="2" col="4">
            <colourRestriction>RED</colourRestriction>
        </cell>
        <cell row="3" col="3">
            <valueRestriction>5</valueRestriction>
        </cell>
        <cell row="3" col="4">
            <colourRestriction>YELLOW</colourRestriction>
        </cell>
        <cell row="4" col="1">
            <colourRestriction>GREEN</colourRestriction>
        </cell>
        <cell row="4" col="2">
            <valueRestriction>3</valueRestriction>
        </cell>
        <cell row="4" col="5">
            <colourRestriction>PURPLE</colourRestriction>
        </cell>
    </grid>
</pattern>

=== michelemarzollo/ing-sw-2018-labate-maffiola-marzollo/src/main/resources/it/polimi/se2018/model/patterns/xmls/firelight.xml
<?xml version="1.0" encoding="UTF-8" ?>

<pattern xmlns="http://se2018.polimi.it/pattern"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://se2018.polimi.it/pattern ../pattern.xsd">
    <name>Firelight</name>
    <difficulty>5</difficulty>
    <grid>
        <cell row="1" col="1">
            <valueRestriction>3</valueRestriction>
        </cell>
        <cell row="1" col="2">
            <valueRestriction>4</valueRestriction>
        </cell>
        <cell row="1" col="3">
            <valueRestriction>1</valueRestriction>
        </cell>
        <cell row="1" col="4">
            <valueRestriction>5</valueRestriction>
        </cell>
        <cell row="2" col="2">
            <valueRestriction>6</valueRestriction>
        </cell>
        <cell row="2" col="3">
            <valueRestriction>2</valueRestriction>
        </cell>
        <cell row="2" col="5">
            <colourRestriction>YELLOW</colourRestriction>
        </cell>
        <cell row="3" col="4">
            <colourRestriction>YELLOW</colourRestriction>
        </cell>
        <cell row="3" col="5">
            <colourRestriction>RED</colourRestriction>
        </cell>
        <cell row="4" col="1">
            <valueRestriction>5</valueRestriction>
        </cell>
        <cell row="4" col="3">
            <colourRestriction>YELLOW</colourRestriction>
        </cell>
        <cell row="4" col="4">
            <colourRestriction>RED</colourRestriction>
        </cell>
        <cell row="4" col="5">
            <valueRestriction>6</valueRestriction>
        </cell>
    </grid>
</pattern>
